swiftmailer:
    url: '%env(MAILER_URL)%'
    spool: { type: 'memory' }
    transport: smtp
    auth_mode: login
    port: 465
    host: smtp.gmail.com
    # Use your gmail account username and password
    username: gmail_username
    password: gmail_password
